### PR TITLE
Modify the schematic for SparkFun rotary encoder

### PR DESCRIPTION
**Pull request by pdp7**
Modify the pins numbering in the schematic component for
the SparkFun Rotary Encoder (COM-09117) so that the pins
are numbered in the same order as the footprint so that
the traces to header can be straight and not diagonal.

### CODE REVIEW

**Comment by pdp7** [comment]
Photos of the PCB:
https://goo.gl/photos/5eCoerMZ7369YQFb9

OSH Park shared project:
https://oshpark.com/shared_projects/DNZ2Ibf6

**Comment by mcous** [comment]
Holy crap I had no idea this library was being used!

This looks mostly good, but I'd like the pin on the schematic to still be called out as "C" because that's what it is on the datasheet. Maybe "GND (C)" or something along those lines?

**Comment by pdp7** [comment]
@mcous yup, it was helpful! https://goo.gl/photos/crp8gj4LS72hnQe67

That is a good point about the label.  I'll change it and push the commit.

**Comment by pdp7** [comment]
@mcous I've renamed GND to C.  "GND (C)" was too long and crowded the component drawing.

**Comment by mcous** [comment]
Thanks a lot!

**Pull request merged**
